;GUTIERREZ LOAEZA CARLOS DE JESUS
;ORDENAMIENTO BURBUJA

;DECLARACI?N DE SEGMENTO DE PILA
PILA SEGMENT STACK
    DB 8 DUP ('STACK_')
PILA ENDS

;DECLARACI?N DE SEGMENTO DE DATOS
DATAS SEGMENT
    TITULO DB 'ORDENAMIENTO BURBUJA: $';TEXTO    
    CADENADES DB 'CADENA DESORDENADA: $';TEXTO
    CADENA DB '5201789624377235791347915','$';CADENA A EVALUAR
    LONGITUD EQU $-CADENA;OBTENER LONGITUD DE CADENA
    SALTO DB 10,13,'$';SALTO DE LINEA
    CADENAORDENADA DB 'CADENA EN ORDEN ASCENDENTE: $';TEXTO
DATAS ENDS

;DECLARACION DE SEGMENTO DE C?DIGO
CODE SEGMENT 'CODE';DATOS DEL PROGRAMA
    MAIN PROC FAR
ASSUME SS:PILA,DS:DATAS,CS:CODE

     ;GUARDAR DATOS Y ASIGNAR
     ;LOS DATOS CON LOS QUE SE TRABAJARA
     PUSH DS
     PUSH 0
     MOV AX, DATAS
     MOV DS,AX
     
     ;LIMPIAR PANTALLA Y COLOR
     MOV AX, 0600H
     MOV BH, 70H
     MOV CX, 0000H
     MOV DX, 184FH
     INT 10H
     
     ;iMPRESION DEL TITULO
     MOV AH, 09H
     LEA DX,TITULO
     INT 21H
     
     ;SALTO DE LINEA
    MOV AH, 09
    MOV DX,OFFSET SALTO;
    INT 21H
     
    ;IMPRESION DE TEXTO
     MOV AH, 09H
    LEA DX,CADENADES
    INT 21H
     
    ;IMPRESION DE LA CADENA A EVALUAR DESORDENADA
     MOV AH, 09H
    LEA DX,CADENA
    INT 21H
    
    ;SALTO DE LINEA
    MOV AH, 09
    MOV DX,OFFSET SALTO;
    INT 21H
    
    ;IMPRESION DE TEXTO
    MOV AH, 09H
    LEA DX,CADENAORDENADA
    INT 21H
     
    ;SE ASIGNA LA LONGITUD DE LA CADENA
    ;AL REGISTRO QUE TRABAJA COMO CONTADOR
    ;EN EL LOOP
    MOV CX,LONGITUD
    SUB CX,2; LONGITUD - 1
    LOOP_1:;INICIO CICLO 1
        PUSH CX ;SE GUARDA EL VALOR
        LEA SI,CADENA  ; X = 0 
        MOV AH,[SI]    ; [SI] = [X]
        MOV AL,[SI+1]  ; [DI] = [Y]
        MOV CX,LONGITUD ; LONGITUD
        SUB CX,2 ;SE RESTA 
        LOOP_2: ;INICIO CICLO 2
            CMP AH,AL ;SE COMPARARA SI ES MAYOR
            JA CAMBIO ;SI LO ES, SE CMBIA DE LUGAR
                      ;EL NUMERO 
            CONTINUAR:;CONTINUAN LAS ITERACIONES
            INC SI ;iNCREMENTAMOS SI
            MOV AH,[SI] ;SE MUEVE AL REGISTRO EL 
                        ;VALOR QUE TIENE [SI]
            MOV AL,[SI+1];SE MUEVE AL REGISTRO EL 
                         ;VALOR QUE TIENE [SI+1] 
        LOOP LOOP_2;FIN DE CICLO 2
        POP CX ;RECUPERAMOS EL VALOR DE CX OCUPADO
               ;EN EL CICLO 1
    LOOP LOOP_1 ;FIN DEL CICLO 1
    
    ;IMPRESION DE LA CADENA ORDENADA
    MOV AH,09H     
    LEA DX,CADENA
    INT 21H
    
    ;TERMINACION DEL PROGRAMA
    SALIR:
    MOV AH,4CH
    INT 21H
    RET
    
    ;REALIZA EL CAMBIO DE LOS VALORES CUANDO
    ;ES MAYOR Y ESTA EN EL LUGAR INCORRECTO
    CAMBIO:
    MOV [SI],AL
    MOV [SI+1],AH
    JMP CONTINUAR
    
    ;FINAL
    MAIN ENDP
CODE ENDS
END MAIN