;CARLOS DE JES?S GUTI?RREZ LOAEZA

;DECLARACI?N DE SEGMENTO DE PILA
PILA SEGMENT PARA STACK 'STACK' 
    DB 62 DUP('STACK')
PILA ENDS

;DECLARACI?N DE SEGMENTO DE DATOS
DATOS SEGMENT 'DATA'
    CADENA DB 'CARLOS LOAEZA','$' ;CADENA A EVALUAR
    NUM EQU $-CADENA ;OBTENER LONGITUD DE CADENA
    TIENE DB 10,13,'LA CANTIDAD DE VOCALES ES:  $' ;TEXTO
    TOTAL DB '  $' ;VARIABLE QUE TENDRA EL TOTAL DE VOCALES
DATOS ENDS

;DECLARACI?N DE SEGMENTO DE C?DIGO
CODE SEGMENT PARA 'CODE' ;INICIAR EL CODIGO DE PROGRAMA
    
    MAIN PROC FAR ;DATOS DEL PROGRAMA
    ASSUME CS:CODE,DS:DATOS,SS:PILA

    ;SE ASIGNAN LOS DATOS A OCUPAR
    MOV AX,DATOS
    MOV DS,AX
    
    ;SE ASIGNA AL ARREGLO LA CADENA
    LEA SI,CADENA
    MOV DX,0000H
    ;SE ASIGNA A CX LA LONGITUD DE LA CADENA
    ;PARA OCUPARSE EN EL LOOP
    MOV CX,NUM
    
    ;CICLO EL CUAL SU FUNCION ES LEER TODAS LAS VOCALES, 
    ;LOS APOSTROFES INDICAN QUE BAN TOMAR EL CONTENIDO 
    ;DE LA POSICION Y ENTONCES COMPARA EL VALOR DE LA 
    ;TECLA DE LA VOCAL EN HEXADESIMAL, LOOP NOS SIRVE 
    ;PARA ITERAR HASTA QUE LLEGUE A CERO, EL REGISTRO 
    ;CX MANTIENE UNA CUENTA ACTIVA DE LAS VESES QUE 
    ;SEAN ITERADO, Y AL COMPLETAR UN CICLO SE 
    ;DECREMENTA EN UNO HASTA LLEGAR A CERO.
    
    ETI:
    MOV AL,[SI]
    CMP AL,61H        ;a COMPARA LETRA a
    JE VOCAL
    CMP AL,41H        ;A COMPARA LETRA A
    JE VOCAL
    CMP AL,65H        ;e COMPARA LETRA e
    JE VOCAL
    CMP AL,45H        ;E COMPARA LETRA E
    JE VOCAL
    CMP AL,69H        ;i COMPARA LETRA i
    JE VOCAL
    CMP AL,49H        ;I COMPARA LETRA I
    JE VOCAL
    CMP AL,6FH        ;o COMPARA LETRA o
    JE VOCAL
    CMP AL,4FH        ;O COMPARA LETRA O
    JE VOCAL
    CMP AL,75H        ;u COMPARA LETRA u
    JE VOCAL
    CMP AL,55H        ;U COMPARA LETRA U
    JE VOCAL

    REGRESA:; AL TERMINAR DE COMPARAR LA
    ;LETRA, REGRESA LA SIGUIENTE POSICION
    ;PARA HACER LA COMPARACI?N DE NUEVO
    INC SI
    LOOP ETI;FIN DEL LOOP
    
    
    LEA SI, TOTAL ;SE LE ASIGNA A SI
                ;EL TOTAL DE VOCALES
    MOV AX,DX ;SE MUEVE EL REGISTRO
    AAA ;FORMATO DE SUMA PARA 2 DIGITOS
    ADD AH,30H ;SE SUMA AL REGISTRO PARA
               ;QUE PUEDA SER IMPRIMIBLE
    MOV [SI],AH ;SE ASIGNA EL VALOR
                ;YA CON EL FORMATO
    INC SI ;SE INCREMENTA 
    ADD AL,30H ;SE SUMA AL REGISTRO PARA
               ;QUE PUEDA SER IMPRIMIBLE
    MOV [SI],AL ;SE ASIGNA EL VALOR
                ;YA CON EL FORMATO
    
    ;SE IMPRIME LA CADENA EVALUADA
    LEA DX,CADENA
    MOV AH,09H
    INT 21H
    
    ;TEXTO 
    LEA DX,TIENE
    MOV AH,09H
    INT 21H
    
    ;SE IMPRIME LA CANTIDAD DE VOCALES
    LEA DX,TOTAL
    MOV AH,09H
    INT 21H
    JMP SALIR
    
    ;SI ES VOCAL, SE INCREMENTA DL
    VOCAL:
    INC DL
    JMP REGRESA
    
    ;FINALIZAR PROGRAMA
    SALIR:
    MOV AX,4C00H
    INT 21H
    
CODE ENDS
END MAIN
