;@UTOR GUTIERREZ LOAEZA CARLOS DE JESUS
;SUMA DE 3 NUMEROS

PILA SEGMENT STACK "STACK"
     DB 40H DUP(0)
PILA ENDS

DATOS SEGMENT ;SEGMENTO DE DATOS
    CAD1 DB 'INGRESA UN NUMERO: ','$'
    CAD2 DB 'INGRESA OTRO NUMERO: ','$'
    CAD3 DB 'INGRESA OTRO NUMERO: ','$'
    CAD4 DB 'RESULTADO SUMA: ','$'
    SALTO DB 10,13,'$'
DATOS ENDS

CODE SEGMENT
     ASSUME CS:CODE,SS:PILA, DS:DATOS

START PROC

    PUSH DS
    PUSH 0
    MOV AX, DATOS
    MOV DS, AX

    ;LIMPIAR PANTALLA
    MOV AX, 0600H
    MOV BH, 47H
    MOV CX, 0000H
    MOV DX, 184FH
    INT 10H
    
    MOV AH, 09 ;IMPRIMIMOS CADENA 1
    MOV DX, OFFSET CAD1
    INT 21H
    
    MOV AH, 01H ;LEER NUMERO 1
    INT 21H
    
    SUB AL,30H ;HACEMOS AJUSTE DEL NUMERO 
    MOV BL,AL ;ASIGNAMOS EL NUMERO A OTRO REGISTRO
    
    MOV AH, 09
    MOV DX,OFFSET SALTO;
    INT 21H
    
    MOV AH, 09 ;IMPRIMIMOS CADENA 2
    MOV DX, OFFSET CAD2
    INT 21H

    MOV AH, 01H ;LEER NUMERO 2
    INT 21H
    
    SUB AL,30H ;HACEMOS AJUSTE DEL NUMERO
    MOV CL,AL ;ASIGNAMOS EL NUMERO A OTRO REGISTRO
    
    MOV AH,09
    MOV DX, OFFSET SALTO
    INT 21H
    
    MOV AH, 09 ;IMPRIMIMOS CADENA 3
    MOV DX, OFFSET CAD3
    INT 21H
    
    MOV AH, 01H ;LEER NUMERO 3
    INT 21H
    
    SUB AL,30H ;HACEMOS AJUSTE DEL NUMERO
    
    ADD  AL,BL   ;SUMA 1  
    AAA    ;AJUSTE ASCII PARA LA SUMA
    ADD AL,CL ;SUMA 2
    AAA ;AJUSTE ASCII PARA LA SUM
    
    OR  AX,3030H ;REALIZA UN OR LOGICO EN EL VALOR
                 ;Y SE ALMACENA EN EL DESTINO INDICADO
    MOV BX,AX ;MOVEMOS A OTRO REGISTRO EL VALOR
    
    MOV AH, 09
    MOV DX,OFFSET SALTO;
    INT 21H
    
    MOV AH, 09 ;IMPRIMIMOS CADENA 4
    MOV DX, OFFSET CAD4
    INT 21H
    
    SUB BH,01H ;AJUSTAMOS
    ;IMPRESION PARTE ALTA
    MOV AH,02H
    MOV DL,BH
    INT 21H
    ;IMPRESION PARTE BAJA
    MOV AH,02
    MOV DL,BL
    INT 21H

    MOV  AX,4C00H  ;TERMINAR EL PROGRAMA
    INT  21H   

START ENDP

CODE ENDS
     END START